user node-red
topic read $SYS/#
topic read classmate/v1/devices/+/telemetry
topic write classmate/v1/devices/+/config
topic write classmate/v1/children/+/events

user parent-poc
topic read classmate/v1/children/+/events
